import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { isSupported } from "firebase/analytics";

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import Script from "next/script";
import { initializeAuth } from "firebase/auth";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <Script defer src="/__/firebase/10.11.0/firebase-app-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-auth-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-database-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-firestore-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-functions-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-messaging-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-storage-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-analytics-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-remote-config-compat.js"></Script>
      <Script defer src="/__/firebase/10.11.0/firebase-performance-compat.js"></Script>
      <Script defer src="/__/firebase/init.js?useEmulator=true"></Script>


      <Script src="https://apis.google.com/js/platform.js" async defer></Script>
      <meta name="google-signin-client_id" content="911079370304-2u99bp5ef59s8dl16a97gslt5dp7fgpm.apps.googleusercontent.com.apps.googleusercontent.com"></meta>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
